config/routes.rb
RuterServer::Application.routes.draw do
  resources :stops

end

app/models/stop.rb
class Stop < ActiveRecord::Base
  attr_accessible :easting, :fare_zone, :latitude, :longitude, :name, :northing, :stop_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  # GET /stops
  # GET /stops.json
  def index
    @stops = Stop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stops }
    end
  end

  # GET /stops/1
  # GET /stops/1.json
  def show
    @stop = Stop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stop }
    end
  end

  # GET /stops/new
  # GET /stops/new.json
  def new
    @stop = Stop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stop }
    end
  end

  # GET /stops/1/edit
  def edit
    @stop = Stop.find(params[:id])
  end

  # POST /stops
  # POST /stops.json
  def create
    @stop = Stop.new(params[:stop])

    respond_to do |format|
      if @stop.save
        format.html { redirect_to @stop, notice: 'Stop was successfully created.' }
        format.json { render json: @stop, status: :created, location: @stop }
      else
        format.html { render action: "new" }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stops/1
  # PUT /stops/1.json
  def update
    @stop = Stop.find(params[:id])

    respond_to do |format|
      if @stop.update_attributes(params[:stop])
        format.html { redirect_to @stop, notice: 'Stop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stops/1
  # DELETE /stops/1.json
  def destroy
    @stop = Stop.find(params[:id])
    @stop.destroy

    respond_to do |format|
      format.html { redirect_to stops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RuterServer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stops/_form.html.erb
<%= form_for(@stop) do |f| %>
  <% if @stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
      <% @stop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stop_id %><br />
    <%= f.number_field :stop_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :northing %><br />
    <%= f.text_field :northing %>
  </div>
  <div class="field">
    <%= f.label :easting %><br />
    <%= f.text_field :easting %>
  </div>
  <div class="field">
    <%= f.label :fare_zone %><br />
    <%= f.number_field :fare_zone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stops/edit.html.erb
<h1>Editing stop</h1>

<%= render 'form' %>

<%= link_to 'Show', @stop %> |
<%= link_to 'Back', stops_path %>

app/views/stops/index.html.erb
<h1>Listing stops</h1>

<table>
  <tr>
    <th>Stop</th>
    <th>Name</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Northing</th>
    <th>Easting</th>
    <th>Fare zone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stops.each do |stop| %>
  <tr>
    <td><%= stop.stop_id %></td>
    <td><%= stop.name %></td>
    <td><%= stop.latitude %></td>
    <td><%= stop.longitude %></td>
    <td><%= stop.northing %></td>
    <td><%= stop.easting %></td>
    <td><%= stop.fare_zone %></td>
    <td><%= link_to 'Show', stop %></td>
    <td><%= link_to 'Edit', edit_stop_path(stop) %></td>
    <td><%= link_to 'Destroy', stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stop', new_stop_path %>

app/views/stops/new.html.erb
<h1>New stop</h1>

<%= render 'form' %>

<%= link_to 'Back', stops_path %>

app/views/stops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stop:</b>
  <%= @stop.stop_id %>
</p>

<p>
  <b>Name:</b>
  <%= @stop.name %>
</p>

<p>
  <b>Latitude:</b>
  <%= @stop.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @stop.longitude %>
</p>

<p>
  <b>Northing:</b>
  <%= @stop.northing %>
</p>

<p>
  <b>Easting:</b>
  <%= @stop.easting %>
</p>

<p>
  <b>Fare zone:</b>
  <%= @stop.fare_zone %>
</p>


<%= link_to 'Edit', edit_stop_path(@stop) %> |
<%= link_to 'Back', stops_path %>